# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HCNImageViewerExample' do
pod 'SDWebImage'
pod 'SVProgressHUD'
end

target 'HCNImageViewerExampleTests' do

end

