# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HCNImageBrowserExample' do
pod 'SDWebImage'
pod 'SVProgressHUD'
end

target 'HCNImageBrowserExampleTests' do

end

